# Generated by config_brpc.sh, don't modify manually
SYSTEM=Linux
HDRS=/usr/local/include/ /usr/local/include/sqlpp11/ /usr/local/include/sqlpp11-mysql/ /usr/local/include/node/  ../../../network/ ../../../utils/ ../../../base/ ../../../httptools/ ../../../examples/sign_server/lib/ ../../../examples/cards/  ../../../examples/cards/keno/ ../../../phxpaxos/include/ ../../../bitcoin/ ../../../lib/ ../../lib/ ../../../tracker/common/ 
LIBS=/usr/local/lib ../../../network ../../../utils ../../../base  ../../../httptools ../../../examples/sign_server/lib ../../../examples/cards ../../../phxpaxos/lib ../../../bitcoin  ../../../lib ../../lib ../../../tracker/common
PROTOC=/usr/local/bin/protoc
#ODB=/home/ubuntu/test/odb/odb-2.4.0-x86_64-linux-gnu/bin/odb
PROTOBUF_HDR=/usr/local/include/
CC=gcc
CXX=g++ -std=gnu++11 
GCC_VERSION=40805
STATIC_LINKINGS= -lbrpc_server -ltbb -lcards -lsign_client  -ltorrent_common -lutils -lnetwork -lbbtbase -lhttptools -lphxpaxos -lglog -lrdkafka -lgflags -lprotobuf -lleveldb -lbtc -lbitcoin -lbitcoin_rpcclient -lbitcoin_util -lbitcoin_crypto_base -lssl -lfc -lsecp256k1 -lev -ljansson -lrestclient-cpp -lcurl -lmpdec -lsqlpp-mysql -lmysqlclient -lz -lhiredis -lboost_system -lboost_thread -lboost_chrono -lboost_filesystem -lboost_date_time -lboost_context -lboost_coroutine -lboost_iostreams 
# -lodb-mysql -lboost_date_time -lboost_system -lodb -lpthread 
DYNAMIC_LINKINGS=-lpthread -lssl -lcrypto -ldl -lz -lrt
CPPFLAGS=-DBRPC_WITH_GLOG=1 -DGFLAGS_NS=google -g
ifeq ($(NEED_LIBPROTOC), 1)
    STATIC_LINKINGS+=-lprotoc
endif
ifeq ($(NEED_GPERFTOOLS), 1)
    $(error "Fail to find gperftools")
endif
#DYNAMIC_LINKINGS+=-lglog
ifeq ($(NEED_GTEST), 1)
    $(error "Fail to find gtest")
endif
